apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: items-api
  links:
    - url: https://github.com/iiethear0/api-server/blob/main/document.docx?raw=true
      title: Download Documentation
  description: A simple CRUD API
  tags:
    - api
    - swagger
spec:
  type: openapi
  lifecycle: production
  owner: middleware
  definition:
    $text: https://github.com/iiethear0/api-server/blob/main/openapi.yaml
