apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: items-api
  links:
    - url: http://localhost:4000/api-docs/#/default/get_api_items
      title: My Dashboard
  description: A simple CRUD API
  tags:
    - api
    - swagger
spec:
  type: openapi
  lifecycle: production
  owner: middleware
  definition:
    $text: https://github.com/iiethear0/api-server/blob/main/openapi.yaml
