apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-demo
  description: A simple CRUD API
  tags:
    - testing
    - anb
spec:
  type: openapi
  lifecycle: production
  owner: teasting team
  definition:
    $text: https://github.com/iiethear0/api-server/blob/main/routes/api.js
