apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  annotations:
    github.com/project-repo: https://github.com/username/api-server
    backstage.io/kubernetes-namespace: default
  owner: Faisal
  name: api-server
  description: API server with Swagger documentation for CRUD operations
  tags:
    - api
    - swagger
    - express
spec:
  type: openapi
  lifecycle: production
  owner: fisal7003@gmail.com
  definition:
  location: http://localhost:4000/api-docs
    $text: |
      openapi: 3.0.0
      info:
        title: CRUD API
        version: 1.0.0
        description: A CRUD API with Swagger documentation
      paths:
        /api/items:
          get:
            summary: Retrieve a list of items
            responses:
              200:
                description: A list of items
        /api/items/{id}:
          get:
            summary: Get an item by ID
            responses:
              200:
                description: The requested item
