apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-server
  links:
    - url: http://localhost:4000/api-docs/#/default/get_api_items
      title: My Dashboard
  description: A simple CRUD API
  tags:
    - api
    - swagger
spec:
  type: openapi
  lifecycle: production
  owner: Faisal
  definition:
    $text: https://github.com/iiethear0/api-server/blob/main/openapi.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: server
spec:
  type: openapi
  lifecycle: production
  owner: Faisal
  system: swagger
  providesApis: [api-server]
