apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-server
  description: A simple CRUD API
  tags:
    - api
    - swagger
spec:
  type: openapi
  lifecycle: production
  owner: Faisal
  definition:
    $text: https://8dd7-51-252-154-73.ngrok-free.app/api-docs/swagger.json
