apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-server-swagger
  description: API server with Swagger documentation for CRUD operations
  tags:
    - api
    - swagger
    - express
spec:
  type: openapi
  lifecycle: production
  owner: fisal7003@gmail.com
  definition:
    location: http://localhost:4000/api-docs
