apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-server
  description: CRUD API for managing items
  tags:
    - api
    - openapi
spec:
  type: openapi
  lifecycle: production
  owner: fisal7003@gmail.com
  definition:
    $text: https://github.com/iiethear0/api-server/blob/main/openapi.yaml
