apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: items-api
  links:
    - url: http://localhost:4000/api-docs/#/default/get_api_items
      title: My Dashboard
  description: A simple CRUD API
  tags:
    - api
    - swagger
spec:
  type: openapi
  lifecycle: production
  owner: fisal7003
  definition:
    $text: https://github.com/iiethear0/api-server/blob/main/openapi.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: middleware
spec:
  type: openapi
  lifecycle: production
  owner: fisal7003
  system: swagger
  providesApis: [items-api]
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: swagger
spec:
  owner: fisal7003
